package com.example.identifruitv2

class ResultsLabels {
    private val labels = arrayOf(
        "apple",
        "apple green",
        "avocado",
        "banana",
        "bell pepper",
        "bignay",
        "bilimbi",
        "black currant",
        "black mullberry",
        "black sapote",
        "bread fruit",
        "caimito",
        "canistel",
        "cantaloupe",
        "carambola",
        "cashew",
        "cherry",
        "chico",
        "cocoa bean",
        "coconut",
        "coffee",
        "custard apple",
        "dragonfruit",
        "durian",
        "grape",
        "green mandarine",
        "guanabana",
        "hawthorn",
        "jackfruit",
        "jamaica cherry",
        "jambul",
        "jocote",
        "kaffir lime",
        "langsat",
        "lemon",
        "lime",
        "longan",
        "lychee",
        "mabolo",
        "macadamia",
        "malay apple",
        "mandarine",
        "mango",
        "mangosteen",
        "manila tamarind",
        "marang",
        "miracle fruit",
        "mountain soursop",
        "nungu",
        "oil palm",
        "olive",
        "orange",
        "papaya",
        "passion fruit",
        "pea",
        "peanut",
        "pear",
        "persimmon",
        "pili nut",
        "pineapple",
        "pomegranate",
        "pomelo",
        "rambutan",
        "raspberry",
        "red mulberry",
        "ridged gourd",
        "salak",
        "santol",
        "strawberry",
        "sugar apple",
        "tamarillo",
        "tamarind",
        "tomato",
        "vanilla",
        "watermelon"
    )

    fun getLabelFromIndex(index: Int): String {
        return labels[index]
    }
}